// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0DxZ96Zuv4grMIsW-WUj4aozDrFmupBw',
    appId: '1:1024722795033:web:5caaa068eac77cc7340888',
    messagingSenderId: '1024722795033',
    projectId: 'fooddeliveryapp-b483a',
    authDomain: 'fooddeliveryapp-b483a.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-b483a.firebasestorage.app',
    measurementId: 'G-JKWVS5W6M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfb6_SOxSFESHRp4Qvzfgq5APWSro1rxk',
    appId: '1:1024722795033:android:85a18e1d21064267340888',
    messagingSenderId: '1024722795033',
    projectId: 'fooddeliveryapp-b483a',
    storageBucket: 'fooddeliveryapp-b483a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTOyDnaAkSWFBxx1v-xeeYHMoNDK6fVaw',
    appId: '1:1024722795033:ios:a5d09847f7ce3cbd340888',
    messagingSenderId: '1024722795033',
    projectId: 'fooddeliveryapp-b483a',
    storageBucket: 'fooddeliveryapp-b483a.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTOyDnaAkSWFBxx1v-xeeYHMoNDK6fVaw',
    appId: '1:1024722795033:ios:a5d09847f7ce3cbd340888',
    messagingSenderId: '1024722795033',
    projectId: 'fooddeliveryapp-b483a',
    storageBucket: 'fooddeliveryapp-b483a.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0DxZ96Zuv4grMIsW-WUj4aozDrFmupBw',
    appId: '1:1024722795033:web:1f4329f7f32d1fde340888',
    messagingSenderId: '1024722795033',
    projectId: 'fooddeliveryapp-b483a',
    authDomain: 'fooddeliveryapp-b483a.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-b483a.firebasestorage.app',
    measurementId: 'G-NH6MS8KBXC',
  );
}
